# Generated by Django 5.1.3 on 2024-11-14 00:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-11-14'),
        ),
    ]
