# Generated by Django 5.1.3 on 2024-12-09 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicos', '0007_especialidade_alter_medico_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
