# Generated by Django 5.1.2 on 2024-11-09 16:04

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(code='invalid_name', message='O nome deve conter apenas letras e espaços.', regex='^[a-zA-Z\\s]+$')])),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('data_de_nascimento', models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-11-09')),
                ('cpf', models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='A senha deve ter pelo menos 8 dígitos.')])),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, related_name='paciente_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='paciente_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
