# Generated by Django 5.1.2 on 2024-11-09 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(14, message='O CPF deve ter 14 dígitos .')]),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='password',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.MinLengthValidator(8, message='A senha deve ter pelo menos 8 dígitos.')]),
        ),
    ]
