# Generated by Django 5.1.3 on 2024-12-09 18:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0007_alter_paciente_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-12-09'),
        ),
    ]
