# Generated by Django 5.1.1 on 2024-10-09 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('medicos', '0001_initial'),
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicos.medicos'),
        ),
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pacientes.pacientes'),
        ),
        migrations.DeleteModel(
            name='Medicos',
        ),
        migrations.DeleteModel(
            name='Pacientes',
        ),
    ]
