# Generated by Django 5.1.3 on 2024-11-14 02:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamentos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamentoconsulta',
            name='hora',
            field=models.TimeField(choices=[(datetime.time(8, 0), '08:00 às 09:00'), (datetime.time(9, 0), '09:00 às 10:00'), (datetime.time(10, 0), '10:00 às 11:00'), (datetime.time(11, 0), '11:00 às 12:00'), (datetime.time(12, 0), '12:00 às 13:00'), (datetime.time(13, 0), '13:00 às 14:00')], default=datetime.time(8, 0)),
        ),
    ]
