# Generated by Django 5.1.2 on 2024-10-21 02:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastro', '0005_delete_medicos_alter_paciente_data_de_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-10-21'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='paciente_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='paciente_permissions_set', to='auth.permission'),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('data_de_nascimento', models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-10-21')),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('crm', models.CharField(max_length=20, unique=True)),
                ('especialidade', models.CharField(blank=True, max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, related_name='medico_set', to='auth.group')),
                ('user_permissions', models.ManyToManyField(blank=True, related_name='medico_permissions_set', to='auth.permission')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
