# Generated by Django 5.1.2 on 2024-10-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='paciente_set', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='password',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='paciente_set', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
