# Generated by Django 5.1.1 on 2024-10-14 14:25

import datetime
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_alter_paciente_groups_alter_paciente_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-10-14', validators=[django.core.validators.MinValueValidator(datetime.date(2024, 10, 14)), django.core.validators.MaxValueValidator(datetime.date(2025, 10, 14))]),
        ),
    ]
