# Generated by Django 5.1.2 on 2024-10-19 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_alter_paciente_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
