# Generated by Django 5.1.2 on 2024-10-20 20:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_paciente_is_staff_alter_paciente_is_superuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Medicos',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='data_de_nascimento',
            field=models.DateField(default=django.utils.timezone.now, help_text='eg. 2024-10-20'),
        ),
    ]
