# Generated by Django 5.1.2 on 2024-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_alter_paciente_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
